# Generated by Django 5.1.7 on 2025-04-05 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
