# Generated by Django 5.1.7 on 2025-04-10 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers_user_bio_user_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('exterior_color', models.CharField(blank=True, max_length=15, null=True)),
                ('interior_color', models.CharField(blank=True, max_length=15, null=True)),
                ('mileage', models.IntegerField()),
                ('engine', models.CharField(blank=True, max_length=10, null=True)),
                ('vin_number', models.CharField(max_length=17, unique=True)),
                ('transmission', models.CharField(blank=True, max_length=25, null=True)),
                ('stock_number', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Financing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('work_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('last_four_digits_social_security_number', models.IntegerField()),
                ('street', models.CharField(max_length=255)),
                ('apartment', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('0', 'Alabama'), ('1', 'Alaska'), ('2', 'Arizona'), ('3', 'Arkansas'), ('4', 'California'), ('5', 'Colorado'), ('6', 'Connecticut'), ('7', 'Delaware'), ('8', 'Florida'), ('9', 'Georgia'), ('10', 'Hawaii'), ('11', 'Idaho'), ('12', 'Illinois'), ('13', 'Indiana'), ('14', 'Iowa'), ('15', 'Kansas'), ('16', 'Kentucky'), ('17', 'Louisiana'), ('18', 'Maine'), ('19', 'Maryland'), ('20', 'Massachusetts'), ('21', 'Michigan'), ('22', 'Minnesota'), ('23', 'Mississippi'), ('24', 'Missouri'), ('25', 'Montana'), ('26', 'Nebraska'), ('27', 'Nevada'), ('28', 'New Hampshire'), ('29', 'New Jersey'), ('30', 'New Mexico'), ('31', 'New York'), ('32', 'North Carolina'), ('33', 'North Dakota'), ('34', 'Ohio'), ('35', 'Oklahoma'), ('36', 'Oregon'), ('37', 'Pennsylvania'), ('38', 'Rhode Island'), ('39', 'South Carolina'), ('40', 'South Dakota'), ('41', 'Tennessee'), ('42', 'Texas'), ('43', 'Utah'), ('44', 'Vermont'), ('45', 'Virginia'), ('46', 'Washington'), ('47', 'West Virginia'), ('48', 'Wisconsin'), ('49', 'Wyoming')], max_length=100)),
                ('zip_code', models.IntegerField()),
                ('residence_status', models.CharField(blank=True, choices=[('0', 'Rent'), ('1', 'Own')], max_length=4, null=True)),
                ('landlord_mortgage_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('rent_mortgage_monthly_amount', models.IntegerField()),
                ('time_at_current_residence', models.CharField(choices=[('0', '0 years'), ('1', '1 years'), ('2', '2 years'), ('3', '3 years'), ('4', '4 years'), ('5', '5 years'), ('6', '6 years'), ('7', '7 years'), ('8', '8 years'), ('9', '9 years'), ('10', '10 years'), ('11', '11 years'), ('12', '12 years'), ('13', '13 years'), ('14', '14 years'), ('15', '15 years'), ('16', '16 years'), ('17', '17 years'), ('18', '18 years'), ('19', '19 years'), ('20', '20 years'), ('21', '21 years'), ('22', '22 years'), ('23', '23 years'), ('24', '24 years'), ('25', '25 years'), ('26', '26 years'), ('27', '27 years'), ('28', '28 years'), ('29', '29 years'), ('30', '30 years'), ('31', '31 years'), ('32', '32 years'), ('33', '33 years'), ('34', '34 years'), ('35', '35 years'), ('36', '36 years'), ('37', '37 years'), ('38', '38 years'), ('39', '39 years'), ('40', '40 years'), ('41', '41 years'), ('42', '42 years'), ('43', '43 years'), ('44', '44 years'), ('45', '45 years'), ('46', '46 years'), ('47', '47 years'), ('48', '48 years'), ('49', '49 years'), ('45', '50 years')], max_length=10)),
                ('previous_residence', models.CharField(blank=True, choices=[('0', 'Rent'), ('1', 'Own')], max_length=4, null=True)),
                ('previous_street', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_apartment', models.CharField(blank=True, max_length=255, null=True)),
                ('city_2', models.CharField(blank=True, max_length=100, null=True)),
                ('state_2', models.CharField(blank=True, choices=[('0', 'Alabama'), ('1', 'Alaska'), ('2', 'Arizona'), ('3', 'Arkansas'), ('4', 'California'), ('5', 'Colorado'), ('6', 'Connecticut'), ('7', 'Delaware'), ('8', 'Florida'), ('9', 'Georgia'), ('10', 'Hawaii'), ('11', 'Idaho'), ('12', 'Illinois'), ('13', 'Indiana'), ('14', 'Iowa'), ('15', 'Kansas'), ('16', 'Kentucky'), ('17', 'Louisiana'), ('18', 'Maine'), ('19', 'Maryland'), ('20', 'Massachusetts'), ('21', 'Michigan'), ('22', 'Minnesota'), ('23', 'Mississippi'), ('24', 'Missouri'), ('25', 'Montana'), ('26', 'Nebraska'), ('27', 'Nevada'), ('28', 'New Hampshire'), ('29', 'New Jersey'), ('30', 'New Mexico'), ('31', 'New York'), ('32', 'North Carolina'), ('33', 'North Dakota'), ('34', 'Ohio'), ('35', 'Oklahoma'), ('36', 'Oregon'), ('37', 'Pennsylvania'), ('38', 'Rhode Island'), ('39', 'South Carolina'), ('40', 'South Dakota'), ('41', 'Tennessee'), ('42', 'Texas'), ('43', 'Utah'), ('44', 'Vermont'), ('45', 'Virginia'), ('46', 'Washington'), ('47', 'West Virginia'), ('48', 'Wisconsin'), ('49', 'Wyoming')], max_length=100, null=True)),
                ('zip_code_2', models.IntegerField(blank=True, null=True)),
                ('place_of_employment', models.CharField(blank=True, max_length=100, null=True)),
                ('street_3', models.CharField(blank=True, max_length=255, null=True)),
                ('city_3', models.CharField(blank=True, max_length=100, null=True)),
                ('state_3', models.CharField(blank=True, choices=[('0', 'Alabama'), ('1', 'Alaska'), ('2', 'Arizona'), ('3', 'Arkansas'), ('4', 'California'), ('5', 'Colorado'), ('6', 'Connecticut'), ('7', 'Delaware'), ('8', 'Florida'), ('9', 'Georgia'), ('10', 'Hawaii'), ('11', 'Idaho'), ('12', 'Illinois'), ('13', 'Indiana'), ('14', 'Iowa'), ('15', 'Kansas'), ('16', 'Kentucky'), ('17', 'Louisiana'), ('18', 'Maine'), ('19', 'Maryland'), ('20', 'Massachusetts'), ('21', 'Michigan'), ('22', 'Minnesota'), ('23', 'Mississippi'), ('24', 'Missouri'), ('25', 'Montana'), ('26', 'Nebraska'), ('27', 'Nevada'), ('28', 'New Hampshire'), ('29', 'New Jersey'), ('30', 'New Mexico'), ('31', 'New York'), ('32', 'North Carolina'), ('33', 'North Dakota'), ('34', 'Ohio'), ('35', 'Oklahoma'), ('36', 'Oregon'), ('37', 'Pennsylvania'), ('38', 'Rhode Island'), ('39', 'South Carolina'), ('40', 'South Dakota'), ('41', 'Tennessee'), ('42', 'Texas'), ('43', 'Utah'), ('44', 'Vermont'), ('45', 'Virginia'), ('46', 'Washington'), ('47', 'West Virginia'), ('48', 'Wisconsin'), ('49', 'Wyoming')], max_length=100, null=True)),
                ('zip_code_3', models.IntegerField(blank=True, null=True)),
                ('occupation', models.CharField(max_length=100)),
                ('business_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('time_at_current_employer', models.CharField(choices=[('0', '0 years'), ('1', '1 years'), ('2', '2 years'), ('3', '3 years'), ('4', '4 years'), ('5', '5 years'), ('6', '6 years'), ('7', '7 years'), ('8', '8 years'), ('9', '9 years'), ('10', '10 years'), ('11', '11 years'), ('12', '12 years'), ('13', '13 years'), ('14', '14 years'), ('15', '15 years'), ('16', '16 years'), ('17', '17 years'), ('18', '18 years'), ('19', '19 years'), ('20', '20 years'), ('21', '21 years'), ('22', '22 years'), ('23', '23 years'), ('24', '24 years'), ('25', '25 years'), ('26', '26 years'), ('27', '27 years'), ('28', '28 years'), ('29', '29 years'), ('30', '30 years'), ('31', '31 years'), ('32', '32 years'), ('33', '33 years'), ('34', '34 years'), ('35', '35 years'), ('36', '36 years'), ('37', '37 years'), ('38', '38 years'), ('39', '39 years'), ('40', '40 years'), ('41', '41 years'), ('42', '42 years'), ('43', '43 years'), ('44', '44 years'), ('45', '45 years'), ('46', '46 years'), ('47', '47 years'), ('48', '48 years'), ('49', '49 years'), ('45', '50 years')], max_length=10)),
                ('gross_salary', models.IntegerField(blank=True, null=True)),
                ('net_salary', models.IntegerField()),
                ('other_income', models.IntegerField(blank=True, null=True)),
                ('previous_employment', models.CharField(blank=True, max_length=100, null=True)),
                ('street_4', models.CharField(blank=True, max_length=255, null=True)),
                ('city_4', models.CharField(blank=True, max_length=100, null=True)),
                ('state_4', models.CharField(blank=True, choices=[('0', 'Alabama'), ('1', 'Alaska'), ('2', 'Arizona'), ('3', 'Arkansas'), ('4', 'California'), ('5', 'Colorado'), ('6', 'Connecticut'), ('7', 'Delaware'), ('8', 'Florida'), ('9', 'Georgia'), ('10', 'Hawaii'), ('11', 'Idaho'), ('12', 'Illinois'), ('13', 'Indiana'), ('14', 'Iowa'), ('15', 'Kansas'), ('16', 'Kentucky'), ('17', 'Louisiana'), ('18', 'Maine'), ('19', 'Maryland'), ('20', 'Massachusetts'), ('21', 'Michigan'), ('22', 'Minnesota'), ('23', 'Mississippi'), ('24', 'Missouri'), ('25', 'Montana'), ('26', 'Nebraska'), ('27', 'Nevada'), ('28', 'New Hampshire'), ('29', 'New Jersey'), ('30', 'New Mexico'), ('31', 'New York'), ('32', 'North Carolina'), ('33', 'North Dakota'), ('34', 'Ohio'), ('35', 'Oklahoma'), ('36', 'Oregon'), ('37', 'Pennsylvania'), ('38', 'Rhode Island'), ('39', 'South Carolina'), ('40', 'South Dakota'), ('41', 'Tennessee'), ('42', 'Texas'), ('43', 'Utah'), ('44', 'Vermont'), ('45', 'Virginia'), ('46', 'Washington'), ('47', 'West Virginia'), ('48', 'Wisconsin'), ('49', 'Wyoming')], max_length=100, null=True)),
                ('zip_code_4', models.IntegerField(blank=True, null=True)),
                ('previous_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_employer_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('time_at_previous_employer', models.CharField(blank=True, choices=[('0', '0 years'), ('1', '1 years'), ('2', '2 years'), ('3', '3 years'), ('4', '4 years'), ('5', '5 years'), ('6', '6 years'), ('7', '7 years'), ('8', '8 years'), ('9', '9 years'), ('10', '10 years'), ('11', '11 years'), ('12', '12 years'), ('13', '13 years'), ('14', '14 years'), ('15', '15 years'), ('16', '16 years'), ('17', '17 years'), ('18', '18 years'), ('19', '19 years'), ('20', '20 years'), ('21', '21 years'), ('22', '22 years'), ('23', '23 years'), ('24', '24 years'), ('25', '25 years'), ('26', '26 years'), ('27', '27 years'), ('28', '28 years'), ('29', '29 years'), ('30', '30 years'), ('31', '31 years'), ('32', '32 years'), ('33', '33 years'), ('34', '34 years'), ('35', '35 years'), ('36', '36 years'), ('37', '37 years'), ('38', '38 years'), ('39', '39 years'), ('40', '40 years'), ('41', '41 years'), ('42', '42 years'), ('43', '43 years'), ('44', '44 years'), ('45', '45 years'), ('46', '46 years'), ('47', '47 years'), ('48', '48 years'), ('49', '49 years'), ('45', '50 years')], max_length=10, null=True)),
                ('name_of_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('account_types', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_bank_2', models.CharField(blank=True, max_length=100, null=True)),
                ('account_types_2', models.CharField(blank=True, max_length=100, null=True)),
                ('lender', models.CharField(blank=True, max_length=100, null=True)),
                ('finance_method', models.CharField(choices=[('0', 'Finance'), ('1', 'Lease')], max_length=10)),
                ('monthly_payment', models.IntegerField()),
                ('total_debt', models.IntegerField(blank=True, null=True)),
                ('length_of_loan', models.CharField(blank=True, choices=[('0', '0 years'), ('1', '1 year'), ('2', '2 years'), ('3', '3 years'), ('4', '4 years'), ('5', '5 years')], max_length=10, null=True)),
                ('body', models.TextField(blank=True, max_length=500, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars_photos/')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='user.car')),
            ],
        ),
    ]
